# Generated by Django 5.1 on 2026-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_is_published_news_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrica_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
