# Generated by Django 6.0.6 on 2026-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesettings_yandex_metrica_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_title',
            field=models.CharField(blank=True, default='Instagram', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_title',
            field=models.CharField(blank=True, default='Telegram Bot', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel_title',
            field=models.CharField(blank=True, default='Telegram Channel', max_length=100),
        ),
    ]
