# Generated by Django 6.0.6 on 2026-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sitesettings_instagram_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='kind',
            field=models.CharField(choices=[('message', 'Murojaat'), ('booking', "Bron so'rovi")], default='message', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
