# Generated by Django 6.0.6 on 2026-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactmessage_kind_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
