# Generated by Django 6.0.6 on 2026-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_feature_and_why_us_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('label_uz', models.CharField(max_length=100, null=True)),
                ('label_ru', models.CharField(max_length=100, null=True)),
                ('label_en', models.CharField(max_length=100, null=True)),
                ('placement', models.CharField(choices=[('hero', 'Faqat Hero (bosh ekran)'), ('stats', 'Faqat Statistika seksiyasi'), ('both', 'Ikkalasida ham')], default='both', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
    ]
