# Generated by Django 6.0.6 on 2026-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_statitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_body_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_seo_title_uz',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_seo_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_seo_body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_seo_body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_seo_body_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
