# Generated by Django 6.0.6 on 2026-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_seo_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_label_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_label_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_label_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_features',
            field=models.TextField(blank=True, help_text="Har qator bitta xususiyat (checkmark qatori). Bo'sh qoldirilsa — default 4 ta qator."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_features_en',
            field=models.TextField(blank=True, help_text="Har qator bitta xususiyat (checkmark qatori). Bo'sh qoldirilsa — default 4 ta qator.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_features_ru',
            field=models.TextField(blank=True, help_text="Har qator bitta xususiyat (checkmark qatori). Bo'sh qoldirilsa — default 4 ta qator.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_features_uz',
            field=models.TextField(blank=True, help_text="Har qator bitta xususiyat (checkmark qatori). Bo'sh qoldirilsa — default 4 ta qator.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_badge_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_badge_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_badge_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_desc_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_cta_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
