# Generated by Django 6.0.6 on 2026-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remaining_content_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Sayt havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
