# Generated by Django 6.0.6 on 2026-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_custom_css',
            field=models.TextField(blank=True, verbose_name='Dashboard custom CSS'),
        ),
    ]
