# Generated by Django 6.0.6 on 2026-06-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sitesettings_dashboard_custom_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='dashboard_custom_css',
        ),
    ]
