# Generated by Django 5.1 on 2026-06-07 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Anonim mijoz identifikatori (localStorage'dan)", verbose_name='Visitor UUID')),
                ('visitor_name', models.CharField(blank=True, max_length=100, verbose_name='Ismi')),
                ('visitor_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('pending', 'Kutilmoqda'), ('closed', 'Yopilgan')], db_index=True, default='open', max_length=20, verbose_name='Holat')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID')),
                ('telegram_topic_id', models.IntegerField(blank=True, help_text='Forum-topic ID — har suhbat alohida topic', null=True, verbose_name='Telegram Topic ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan xodim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name="Foydalanuvchi (ro'yxatdan o'tgan bo'lsa)")),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('visitor', 'Tashrif buyuruvchi'), ('staff', 'Xodim'), ('bot', 'Bot'), ('system', 'Tizim')], default='visitor', max_length=10, verbose_name='Yuboruvchi turi')),
                ('via', models.CharField(choices=[('web', 'Sayt'), ('telegram', 'Telegram'), ('dashboard', 'Dashboard')], default='web', max_length=20, verbose_name='Kanal')),
                ('text', models.TextField(verbose_name='Matn')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qildi")),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation', verbose_name='Suhbat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name="Yuboruvchi (xodim bo'lsa)")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
    ]
