# Generated by Django 6.0.6 on 2026-06-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_window', models.PositiveIntegerField(default=120, help_text='Bir stolga shu oraliq ichida ikkinchi bron qabul qilinmaydi.', verbose_name='Ziddiyat oynasi (daqiqa)')),
                ('open_time', models.TimeField(default='10:00', verbose_name='Bron qabul boshlanishi')),
                ('close_time', models.TimeField(default='23:00', verbose_name='Bron qabul tugashi')),
                ('advance_days', models.PositiveIntegerField(default=30, help_text="Bugundan necha kun oldinga bron qilsa bo'ladi.", verbose_name='Oldindan necha kun')),
                ('is_open', models.BooleanField(default=True, help_text="O'chirilsa — sayt bron formasi vaqtincha yopiladi.", verbose_name='Bron qabul qilinmoqda')),
            ],
            options={
                'verbose_name': 'Bron sozlamalari',
                'verbose_name_plural': 'Bron sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('bg_image', models.ImageField(blank=True, help_text='2D sxema uchun ixtiyoriy fon (zona plani).', null=True, upload_to='zones/', verbose_name='Sxema fon rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('consumed', models.BooleanField(default=False, verbose_name='Ishlatildi')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Urinishlar')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'OTP kodi',
                'verbose_name_plural': 'OTP kodlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='reservation_phone_af9bb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Masalan: 12, A1, VIP-3', max_length=20, verbose_name='Stol raqami/nomi')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name="Sig'im (kishi)")),
                ('shape', models.CharField(choices=[('square', 'Kvadrat'), ('round', 'Dumaloq'), ('rect', "To'rtburchak")], default='square', max_length=10, verbose_name='Shakl')),
                ('pos_x', models.FloatField(default=0, verbose_name='X koordinata')),
                ('pos_y', models.FloatField(default=0, verbose_name='Y koordinata')),
                ('width', models.FloatField(default=60, verbose_name='Kenglik')),
                ('height', models.FloatField(default=60, verbose_name='Balandlik')),
                ('status', models.CharField(choices=[('free', "Bo'sh"), ('occupied', 'Band')], default='free', help_text='Hozirgi jonli holat — manager boshqaradi.', max_length=10, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('model_object_id', models.CharField(blank=True, help_text="glTF/GLB modeldagi shu stol obyektining nomi (bog'lash uchun).", max_length=64, verbose_name='3D model obyekt ID')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ['zone__order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Vaqt')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Kishi soni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('seated', 'Joylashdi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('no_show', 'Kelmadi')], default='pending', max_length=12, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP tasdiqlangan')),
                ('source', models.CharField(choices=[('website_2d', 'Sayt (2D sxema)'), ('website_3d', 'Sayt (3D)'), ('phone', 'Telefon'), ('walk_in', 'Restoranda'), ('other', 'Boshqa')], default='website_2d', max_length=12, verbose_name='Manba')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'), models.Index(fields=['table', 'date'], name='reservation_table_i_ad4cea_idx'), models.Index(fields=['customer_phone'], name='reservation_custome_f5a4d1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('zone', 'number'), name='uniq_table_number_per_zone'),
        ),
    ]
