# Generated by Django 5.1 on 2026-06-07 11:56

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='+998 XX XXX-XX-XX formatida', max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('customer', 'Mijoz'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('customer', 'Mijoz'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='waiter', max_length=20, verbose_name='Rol')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Lavozim')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Ishga qabul sanasi')),
                ('pin_hash', models.CharField(blank=True, help_text='4 raqamli PIN kod hashlangan holda saqlanadi', max_length=128, verbose_name='PIN hash')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Xodim profili',
                'verbose_name_plural': 'Xodimlar profillari',
            },
        ),
    ]
