# Generated by Django 5.1 on 2026-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('courier', 'Kuryer'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='waiter', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('courier', 'Kuryer'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Rol'),
        ),
    ]
