# Generated by Django 6.0.6 on 2026-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='waiter', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Rol'),
        ),
    ]
