# Generated by Django 6.0.6 on 2026-06-17 10:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffprofile_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='pin_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='waiter', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Ixtiyoriy aloqa raqami (login uchun ishlatilmaydi)', max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Ofitsiant'), ('barman', 'Barman'), ('accountant', 'Bugalter'), ('manager', 'Menejer'), ('owner', 'Ega'), ('admin', 'Admin')], default='waiter', max_length=20, verbose_name='Rol'),
        ),
    ]
