# Generated by Django 6.0.6 on 2026-06-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Teg nomi')),
                ('color', models.CharField(blank=True, default='secondary', help_text='Bootstrap rang nomi: primary, success, warning, danger, info, secondary', max_length=20, verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(help_text='+998 XX XXX-XX-XX', max_length=20, unique=True, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kun")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jins')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('telegram_user_id', models.CharField(blank=True, max_length=32, verbose_name='Telegram user ID')),
                ('source', models.CharField(choices=[('walk_in', 'Restoranda'), ('website', 'Veb-sayt'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('referral', "Tavsiya (do'st)"), ('other', 'Boshqa')], default='walk_in', max_length=20, verbose_name='Manba')),
                ('sms_consent', models.BooleanField(default=True, verbose_name='SMS rozilik')),
                ('email_consent', models.BooleanField(default=True, verbose_name='Email rozilik')),
                ('telegram_consent', models.BooleanField(default=True, verbose_name='Telegram rozilik')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi akkaunti')),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='crm.tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crm_custome_created_76bb99_idx')],
            },
        ),
    ]
