# Generated by Django 6.0.6 on 2026-06-15 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Kampaniya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Kanal')),
                ('template', models.TextField(help_text='{{first_name}}, {{full_name}}, {{phone}} ishlatish mumkin', verbose_name='Shablon')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirylgan'), ('sent', "Jo'natilgan")], default='draft', max_length=20, verbose_name='Holat')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name="Jo'natish vaqti")),
                ('sent_count', models.IntegerField(default=0, verbose_name='Yuborilan soni')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Muvaffaqiyatsiz soni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratgan')),
                ('tags', models.ManyToManyField(blank=True, help_text="Bo'sh bo'lsa — barcha mijozlarga", related_name='campaigns', to='crm.tag', verbose_name='Teglar (filtr)')),
            ],
            options={
                'verbose_name': 'Kampaniya',
                'verbose_name_plural': 'Kampaniyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Kutayotgan'), ('sent', "Jo'natilgan"), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Holat')),
                ('message_text', models.TextField(blank=True, verbose_name='Xabar')),
                ('error_message', models.TextField(blank=True, verbose_name='Xato xabari')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Jo'natilgan")),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.campaign', verbose_name='Kampaniya')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to='crm.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Kampaniya logi',
                'verbose_name_plural': 'Kampaniya loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='crm_campaig_created_764a49_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='crm_campaig_status_650d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['campaign', 'status'], name='crm_campaig_campaig_939a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['customer'], name='crm_campaig_custome_a8a6fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignlog',
            unique_together={('campaign', 'customer')},
        ),
    ]
