# Generated by Django 6.0.6 on 2026-06-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_campaign_campaignlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sms_template_id',
            field=models.CharField(blank=True, help_text="Faqat SMS uchun: TextUp kabinetida tasdiqlangan shablonning templateId'si. Bo'sh bo'lsa, matn TextUp moderatsiyasidan o'tmasa rad etilishi mumkin.", max_length=64, verbose_name='SMS shablon ID (TextUp)'),
        ),
    ]
