# Generated by Django 6.0.6 on 2026-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_campaign_sms_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday_sms_sent_year',
            field=models.IntegerField(blank=True, help_text='Bir yilda ikki marta tabriklamaslik uchun: oxirgi tabrik yuborilgan yil.', null=True, verbose_name="Tug'ilgan kun SMS yuborilgan yil"),
        ),
    ]
