# Generated by Django 6.0.6 on 2026-06-25 08:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_birthday_sms_sent_year'),
        ('orders', '0002_order_customer_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text="O'chirilsa — buyurtmalardan ball berilmaydi.", verbose_name='Sodiqlik dasturi yoqilgan')),
                ('earn_percent', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Yetkazilgan buyurtma summasining shu foizi ball sifatida beriladi.', max_digits=5, verbose_name='Ball foizi (%)')),
                ('som_per_point', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text="Ball chegirmaga aylantirilganda: 1 ball necha so'm (kelajakda checkout uchun).", max_digits=8, verbose_name="1 ball qiymati (so'm)")),
                ('silver_threshold', models.IntegerField(default=50000, help_text='Shu umrlik balldan boshlab — Kumush daraja.', verbose_name='Kumush daraja (umrlik ball)')),
                ('gold_threshold', models.IntegerField(default=200000, help_text='Shu umrlik balldan boshlab — Oltin daraja.', verbose_name='Oltin daraja (umrlik ball)')),
            ],
            options={
                'verbose_name': 'Sodiqlik sozlamalari',
                'verbose_name_plural': 'Sodiqlik sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.IntegerField(default=0, help_text="Jami to'plangan ball (daraja shu bo'yicha hisoblanadi; sarflasa kamaymaydi).", verbose_name='Umrlik ballar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Mavjud (sarflanmagan) ball balansi.', verbose_name='Joriy ballar'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earn', "Ball to'plandi"), ('redeem', 'Ball sarflandi'), ('adjust', "Qo'lda tuzatish")], max_length=10, verbose_name='Turi')),
                ('points', models.IntegerField(help_text="Musbat — qo'shildi, manfiy — ayrildi.", verbose_name='Ball')),
                ('balance_after', models.IntegerField(default=0, verbose_name='Keyingi balans')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='crm.customer', verbose_name='Mijoz')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Ball harakati',
                'verbose_name_plural': 'Ball harakatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='crm_loyalty_custome_dfcfdb_idx'), models.Index(fields=['order'], name='crm_loyalty_order_i_7705fd_idx')],
            },
        ),
    ]
