# Generated by Django 6.0.6 on 2026-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_loyaltysettings_customer_lifetime_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipients_raw',
            field=models.TextField(blank=True, help_text="Har qatorda yoki vergul bilan telefon raqamlar. To'ldirilsa — SMS faqat shu raqamlarga yuboriladi (teg/mijoz bazasi ishlatilmaydi).", verbose_name="Qo'lda raqamlar"),
        ),
    ]
