# Generated by Django 6.0.6 on 2026-06-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_campaign_recipients_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_to_all_customers',
            field=models.BooleanField(default=False, help_text="Belgilansa — barcha faol, rozilik bergan mijozlarga yuboriladi (guruh tanlovi e'tiborsiz qoladi).", verbose_name='Barcha mijozlarga'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recipients_raw',
            field=models.TextField(blank=True, help_text="Har qatorda yoki vergul bilan telefon raqamlar. Guruh/barcha mijozlar bilan birga ishlatilsa — bu raqamlar ham qo'shiladi (takrorlanadiganlari chiqarib tashlanadi).", verbose_name="Qo'lda raqamlar"),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tanlangan guruh(lar)dagi mijozlarga yuboriladi.', related_name='campaigns', to='crm.tag', verbose_name='Guruhlar (teglar)'),
        ),
    ]
