# Generated by Django 5.1 on 2026-06-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Rasmi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('prep_time', models.PositiveIntegerField(default=15, verbose_name='Tayyorlanish vaqti (daqiqa)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ['category', 'name'],
            },
        ),
    ]
