# Generated by Django 5.1 on 2026-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
