# Generated by Django 6.0.6 on 2026-06-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Bitta taom bir nechta kategoriyada bo'lishi mumkin", related_name='dishes', to='menu.category', verbose_name='Kategoriyalar'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes_legacy', to='menu.category', verbose_name='Kategoriya (eski)'),
        ),
    ]
