# Generated by Django 6.0.6 on 2026-06-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_migrate_category_to_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
    ]
