# Generated by Django 6.0.6 on 2026-06-22 10:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0006_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text="O'chirilsa — sayt buyurtma berishni vaqtincha to'xtatadi.", verbose_name='Buyurtma qabul qilinmoqda')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Shu summadan kam buyurtma qabul qilinmaydi (0 — cheklov yo'q).", max_digits=12, verbose_name='Minimum buyurtma summasi')),
            ],
            options={
                'verbose_name': 'Buyurtma sozlamalari',
                'verbose_name_plural': 'Buyurtma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Buyurtma vaqtidagi jami summa (DB narxlaridan hisoblangan).', max_digits=12, verbose_name='Jami summa')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', help_text="Mijoz tanlovi (ma'lumot uchun — manager telefonda aniqlashtiradi).", max_length=10, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=10, verbose_name='Holat')),
                ('reject_reason', models.TextField(blank=True, help_text='Buyurtma rad etilsa — sababi (manager kiritadi).', verbose_name='Rad etish sababi')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rad etilgan vaqt')),
                ('source', models.CharField(default='web', max_length=20, verbose_name='Manba')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name="Kim ko'rib chiqdi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=120, verbose_name='Taom nomi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.dish', verbose_name='Taom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma satri',
                'verbose_name_plural': 'Buyurtma satrlari',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(default='order', max_length=20, verbose_name='Maqsad')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('consumed', models.BooleanField(default=False, verbose_name='Ishlatildi')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Urinishlar')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'OTP kodi',
                'verbose_name_plural': 'OTP kodlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='orders_otpc_phone_5a9d2d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='orders_orde_phone_7bc88b_idx'),
        ),
    ]
