# Generated by Django 6.0.6 on 2026-06-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_birthday_sms_sent_year'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.customer', verbose_name='Mijoz (CRM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('completed', 'Yetkazildi'), ('rejected', 'Bekor qilindi')], db_index=True, default='new', max_length=10, verbose_name='Holat'),
        ),
    ]
