# Generated by Django 5.1 on 2026-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mijoz ismi'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mijoz telefoni'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik (lng)'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Olib ketish vaqti'),
        ),
    ]
