# Generated by Django 5.1 on 2026-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Marketingga rozilik'),
        ),
    ]
