# Generated by Django 5.1 on 2026-06-12 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_marketing_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AddField(
            model_name='order',
            name='daily_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Kunlik tartib #'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Yo'lga chiqqan vaqt"),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_daily_id',
            field=models.PositiveIntegerField(blank=True, help_text='Faqat delivery buyurtmalar uchun', null=True, verbose_name='Tur tartib #'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('cooking', 'Tayyorlanmoqda'), ('delivering', "Yo'lda"), ('preparing', 'Tayyorlanmoqda (stol)'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
