# Generated by Django 5.1 on 2026-06-07 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=200, verbose_name='Bot Token')),
                ('admin_chat_id', models.CharField(blank=True, help_text='Bildirishnomalar yuboriluvchi guruh yoki chat ID', max_length=50, verbose_name='Admin Guruh/Chat ID')),
                ('forum_group_id', models.CharField(blank=True, help_text="Chat ko'prigi uchun forum-topic guruh ID", max_length=50, verbose_name='Forum Guruh ID')),
                ('webhook_secret', models.CharField(blank=True, max_length=200, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Telegram sozlamalari',
                'verbose_name_plural': 'Telegram sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='Platforma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qurilma tokeni',
                'verbose_name_plural': 'Qurilma tokenlari',
            },
        ),
    ]
