# Generated by Django 6.0.6 on 2026-06-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Mehmon ID')),
                ('lang', models.CharField(blank=True, max_length=5, verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Chat sessiyasi',
                'verbose_name_plural': 'Chat sessiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Mehmondan'), ('out', 'Adminga/avto')], max_length=3, verbose_name="Yo'nalish")),
                ('text', models.TextField(verbose_name='Matn')),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram message_id')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Avto-javob')),
                ('delivered', models.BooleanField(default=False, verbose_name='Yetkazildi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.chatsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['id'],
            },
        ),
    ]
